development:
  bucket: enjoytheweb-us
  access_key_id: AKIAJ6XCTZWSKUWA7GXA
  secret_access_key: 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
test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: enjoytheweb-us
  access_key_id: AKIAJ6XCTZWSKUWA7GXA
  secret_access_key: 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
